# Site settings
title: Trivial or Wrong
email: omer@sphericalcow.io
description: > # this means to ignore newlines until "baseurl:"
  Machine Learning, Data Science, Programming, Mathematics and Algorithms.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://omersha.github.io/" # the base hostname & protocol for your site
twitter_username: omershamir
github_username:  omersha

# Build settings
markdown: kramdown
highlighter: rouge
#highlighter: pygments
math_engine: mathjax

gems:
  - jekyll-sitemap

collections:
  laws-sausages-and-convnets:
    output: true
