# Site settings
title: Trivial or Wrong
email: 2add@later.com
description: > # this means to ignore newlines until "baseurl:"
  Machine Learning, Data Science, Programming, Mathematics and Algorithms.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://omersha.github.io/" # the base hostname & protocol for your site
twitter_username: omershamir
github_username:  omersha

# Build settings
markdown: kramdown
highlighter: pygments
math_engine: mathjax
